version: '3.8'
services:
  todo_backend:
    build:
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    env_file:
    - .env
    ports:
      - '5000:5000'
  todo_mongodb:
    image: mongo:latest
    restart: always
    env_file:
    - .env
    ports:
      - '27017:27017'
    volumes:
      - todo_db:/data/db
volumes:
  todo_db: